actor_hidden_layers: 1
algo: ppo
critic_hidden_layers: 1
device: cpu
episode_length: 500
game_name: olympics-running
load_episode: 900
load_model: false
load_run: 2
map: 7
max_episodes: 1500
num_frame: 1
render: false
run_dir: map7_use_step_dist_train_by_win
save_interval: 100
seed: 1
shuffle_map: false
train_by_win: true
use_cnn: false
