algo: ppo
device: cpu
episode_length: 500
game_name: olympics-running
load_episode: 900
load_model: false
load_run: 2
map: 4
max_episodes: 1500
render: false
run_dir: map4_use_dist
save_interval: 10
seed: 1
shuffle_map: false
