actor_hidden_layers: 2
algo: ppo
critic_hidden_layers: 1
device: cpu
episode_length: 500
game_name: olympics-running
load_episode: 900
load_model: false
load_run: 2
map: 3
max_episodes: 1500
render: false
run_dir: map3_use_hit_wall_[actor]_2layers
save_interval: 100
seed: 1
shuffle_map: false
