actor_hidden_layers: 1
algo: ppo
critic_hidden_layers: 1
device: cpu
episode_length: 500
game_name: olympics-running
load_episode: 900
load_model: false
load_run: 2
map: 11
max_episodes: 1500
num_frame: 1
render: false
run_dir: map11_use_step_dist
save_interval: 100
seed: 1
shuffle_map: false
use_cnn: false
